version: '3.7'

services:
  frontend:
    image: php:apache
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
        # if changed, please define the path to website/index.php
      - ./website:/var/www/html
    environment:
      - USERNAME=toto
      - PASSWORD=python
    depends_on:
      - backend
    networks:
      - studentappnetword

  backend:
    image: lamtest:latest
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
        # if changed, please define the path to simple_api/student_age.json
      - ./simple_api:/data
    networks:
      - studentappnetword

networks:
  studentappnetword: